new profilers added
ThinkOpenly/lpcpu pull request #1
Opened 2020-04-07 06:19 UTC by prashantph

2020-04-07 16:01 UTC, ThinkOpenly requested changes

2020-04-07 16:01 UTC, ThinkOpenly commented on lpcpu.sh
> +	echo "Setting up slabtop ."
nit: please remove the space after "slabtop"?

2020-04-07 16:01 UTC, ThinkOpenly commented on lpcpu.sh
> +    echo -n '${LPCPUDIR}/postprocess/postprocess-slabtop--dir=.'" --run-number=$RUN_NUMBER --id=$id"
need a space between "slabtop" and "--dir"
actually, I think you are blindly cutting and pasting here.  Your changes do not include a "postprocess-slabtop" script. Do you need one? If there is no such script or need thereof, then you do not need this function at all.

2020-04-07 16:01 UTC, ThinkOpenly commented on lpcpu.sh
> +	 while [ 1 ]; do cpupower monitor -i $interval ;  done  >> $LOGDIR/cpupower.$id.$RUN_NUMBER &
indentation here should be the same as the previous line.

2020-04-07 16:01 UTC, ThinkOpenly commented on lpcpu.sh
> +function setup_postprocess_cpupower() {
As above, I don't think you need this function at all.

2020-04-07 16:01 UTC, ThinkOpenly commented on lpcpu.sh
> +        echo "Setting up cpu_vulnerabilities ."
delete space after "cpu_vulnerabilities"

2020-04-07 16:01 UTC, ThinkOpenly commented on lpcpu.sh
> +       		if [ ! -d  /sys/devices/system/cpu/vulnerabilities ]; then
indentation is way off.

2020-04-07 16:01 UTC, ThinkOpenly commented on lpcpu.sh
> +                	echo "ERROR: cpu_vulnerabilities is not there in /sys."
I would not characterize this as an ERROR. Maybe a warning?  Maybe rephrase to "NOTE: /sys/devices/system/cpu/vulnerabilities not found."

2020-04-07 16:01 UTC, ThinkOpenly commented on lpcpu.sh
> +                	exit 1
I don't think this is sufficiently catastrophic to force an immediate `exit`.

2020-04-07 16:01 UTC, ThinkOpenly commented on lpcpu.sh
> +		cd /sys/devices/system/cpu/vulnerabilities
indentation

2020-04-07 16:01 UTC, ThinkOpenly commented on lpcpu.sh
> +		cd -
Let's change the above 3 lines to:
```
grep . /sys/devices/system/cpu/vulnerabilities/*
```

2020-04-07 16:01 UTC, ThinkOpenly commented on lpcpu.sh
> +        	disown $CPU_VULN_PID
The `grep` should be plenty fast enough to not need the background process handling, so delete the above 2 lines.

2020-04-07 16:01 UTC, ThinkOpenly commented on lpcpu.sh
> +        kill $CPU_VULN_PID
You won't need the `kill` since we're going with the `grep` above.  You may not need this function at all.  Indeed, since this is really running one `grep` command, you could model it on the `sestatus` addition, and just run it without all the other infrastructure. I'd prefer that.

2020-04-07 16:01 UTC, ThinkOpenly commented on lpcpu.sh
> +        #SCHEDSTAT=$(which schedstat)
if you don't need this (and you don't), delete it.

2020-04-07 16:01 UTC, ThinkOpenly commented on lpcpu.sh
> +                echo "ERROR: schedstat is not there in /proc."
reword to "ERROR: /proc/schedstat not found."

2020-04-07 16:01 UTC, ThinkOpenly commented on lpcpu.sh
> +         while [ 1 ]; do cat /proc/schedstat ;  sleep $interval ; done  >> $LOGDIR/schedstat.$id.$RUN_NUMBER &
indentation. also, all spacing should be a single space (no double space).

2020-04-07 16:01 UTC, ThinkOpenly commented on lpcpu.sh
> +        SCHEDCAT_PID=$!
"SCHEDCAT" is cute. Did you intend that spelling? I expected "SCHEDSTAT". Change here and below, of course.

2020-04-07 16:01 UTC, ThinkOpenly commented on lpcpu.sh
> +function setup_postprocess_schedstat() {
delete this function entirely.

2020-04-07 16:01 UTC, ThinkOpenly commented on lpcpu.sh
> +        #SCHEDSTAT=$(which proc_vmstat)
delete this line

2020-04-07 16:01 UTC, ThinkOpenly commented on lpcpu.sh
> +                echo "ERROR: proc_vmstat is not there in /proc."
reword like above comments.

2020-04-07 16:01 UTC, ThinkOpenly commented on lpcpu.sh
> +         while [ 1 ]; do cat /proc/vmstat | grep thp;  sleep $interval ; done  >> $LOGDIR/proc_vmstat.$id.$RUN_NUMBER &
indentation, remove double spaces.

2020-04-07 16:01 UTC, ThinkOpenly commented on lpcpu.sh
> +function setup_postprocess_proc_vmstat() {
delete this function.

2020-05-20 22:46 UTC, ThinkOpenly commented
![](https://github.trello.services/images/mini-trello-icon.png) [LPCPU changes](https://trello.com/c/pw28y3TG/29-lpcpu-changes)

2020-06-17 19:14 UTC, ThinkOpenly requested changes
Prashant, I've identified a number of tiny issues. (Sorry for the trouble.) Fix these, and then we'll get your changes integrated!

2020-06-17 19:14 UTC, ThinkOpenly commented on lpcpu.sh
> +	echo "Setting up cpupower ."
nit: delete space before '.'

2020-06-17 19:14 UTC, ThinkOpenly commented on lpcpu.sh
> +## cpupower##########################################################################################
nit: space betwen "cpupower" and trailing hashes '#'

2020-06-17 19:14 UTC, ThinkOpenly commented on lpcpu.sh
> +## slabtop##########################################################################################
nit: add space between "slabtop" and trailing hashes '#'

2020-06-17 19:14 UTC, ThinkOpenly commented on lpcpu.sh
> +## schedstat##########################################################################################
nit: add space between "schedstat" and trailing hashes '#'

2020-06-17 19:14 UTC, ThinkOpenly commented on lpcpu.sh
> +        echo "Setting up schedstat ."
nit: delete space between "schedstat" and '.'

2020-06-17 19:14 UTC, ThinkOpenly commented on lpcpu.sh
> +                echo "Note: schedstat is not there in /proc."
change to "Warning: /proc/schedstat not found."

2020-06-17 19:14 UTC, ThinkOpenly commented on lpcpu.sh
> +               	echo "Note: cpu_vulnerabilities is not there in /sys."
change to "Warning: /sys/devices/system/cpu/vulnerabilities not found."

2020-06-17 19:14 UTC, ThinkOpenly commented on lpcpu.sh
> +	echo "starting slabtop." | tee -a $LOGDIR/profile-log.$RUN_NUMBER
s/starting/Starting/

2020-06-17 19:14 UTC, ThinkOpenly commented on lpcpu.sh
> +	echo "starting cpupower." | tee -a $LOGDIR/profile-log.$RUN_NUMBER
s/starting/Starting/

2020-06-17 19:14 UTC, ThinkOpenly commented on lpcpu.sh
> +        echo "starting cpu_vulnerabilities." | tee -a $LOGDIR/profile-log.$RUN_NUMBER
s/starting/Starting/

2020-06-17 19:14 UTC, ThinkOpenly commented on lpcpu.sh
> +        echo "starting schedstat." | tee -a $LOGDIR/profile-log.$RUN_NUMBER
s/starting/Starting/

2020-06-17 19:14 UTC, ThinkOpenly commented on lpcpu.sh
> +                echo "Note: proc_vmstat is not there in /proc."
change to "Warning: /proc/vmstat not found."

2020-06-18 02:39 UTC, prashantph commented
Thanks Paul,

I have taken care of the suggested changes and created a pull request.
Can you please add these changes to GIT

Thanks,
Prashant P

On Thu, Jun 18, 2020 at 12:44 AM Paul Clarke <notifications@github.com>
wrote:

> *@ThinkOpenly* requested changes on this pull request.
>
> Prashant, I've identified a number of tiny issues. (Sorry for the
> trouble.) Fix these, and then we'll get your changes integrated!
> ------------------------------
>
> In lpcpu.sh
> <https://github.com/ThinkOpenly/lpcpu/pull/1#discussion_r441771250>:
>
> > +
> +function start_slabtop() {
> +	echo "starting slabtop." | tee -a $LOGDIR/profile-log.$RUN_NUMBER
> +	slabtop -s u -d $interval >> $LOGDIR/slabtop.$id.$RUN_NUMBER &
> +	SLABTOP_PID=$!
> +	disown $SLABTOP_PID
> +}
> +
> +function stop_slabtop() {
> +	echo "Stopping slabtop."
> +	kill $ISLABTOP_PID
> +}
> +
> +## cpupower##########################################################################################
> +function setup_cpupower() {
> +	echo "Setting up cpupower ."
>
> nit: delete space before '.'
> ------------------------------
>
> In lpcpu.sh
> <https://github.com/ThinkOpenly/lpcpu/pull/1#discussion_r441771271>:
>
> > +	fi
> +}
> +
> +function start_slabtop() {
> +	echo "starting slabtop." | tee -a $LOGDIR/profile-log.$RUN_NUMBER
> +	slabtop -s u -d $interval >> $LOGDIR/slabtop.$id.$RUN_NUMBER &
> +	SLABTOP_PID=$!
> +	disown $SLABTOP_PID
> +}
> +
> +function stop_slabtop() {
> +	echo "Stopping slabtop."
> +	kill $ISLABTOP_PID
> +}
> +
> +## cpupower##########################################################################################
>
> nit: space betwen "cpupower" and trailing hashes '#'
> ------------------------------
>
> In lpcpu.sh
> <https://github.com/ThinkOpenly/lpcpu/pull/1#discussion_r441771309>:
>
> > @@ -498,6 +498,111 @@ function setup_postprocess_iostat() {
>      echo
>  }
>
> +#################################################
> +#
> +# 	Security Level (selinux)
> +##
> +sestatus > $LOGDIR/selinux_status.$id.$RUN_NUMBER
> +
> +
> +## slabtop##########################################################################################
>
> nit: add space between "slabtop" and trailing hashes '#'
> ------------------------------
>
> In lpcpu.sh
> <https://github.com/ThinkOpenly/lpcpu/pull/1#discussion_r441772809>:
>
> > +
> +## cpu_vulnerabilities##########################################################################################
> +
> +function setup_cpu_vulnerabilities() {
> +        echo "Setting up cpu_vulnerabilities."
> +       	if [ ! -d  /sys/devices/system/cpu/vulnerabilities ]; then
> +               	echo "Note: cpu_vulnerabilities is not there in /sys."
> +       	fi
> +}
> +
> +function start_cpu_vulnerabilities() {
> +        echo "starting cpu_vulnerabilities." | tee -a $LOGDIR/profile-log.$RUN_NUMBER
> +       	grep . /sys/devices/system/cpu/vulnerabilities/* >> $LOGDIR/cpu_vulnerabilities.$id.$RUN_NUMBER
> +}
> +
> +## schedstat##########################################################################################
>
> nit: add space between "schedstat" and trailing hashes '#'
> ------------------------------
>
> In lpcpu.sh
> <https://github.com/ThinkOpenly/lpcpu/pull/1#discussion_r441772988>:
>
> > +
> +function setup_cpu_vulnerabilities() {
> +        echo "Setting up cpu_vulnerabilities."
> +       	if [ ! -d  /sys/devices/system/cpu/vulnerabilities ]; then
> +               	echo "Note: cpu_vulnerabilities is not there in /sys."
> +       	fi
> +}
> +
> +function start_cpu_vulnerabilities() {
> +        echo "starting cpu_vulnerabilities." | tee -a $LOGDIR/profile-log.$RUN_NUMBER
> +       	grep . /sys/devices/system/cpu/vulnerabilities/* >> $LOGDIR/cpu_vulnerabilities.$id.$RUN_NUMBER
> +}
> +
> +## schedstat##########################################################################################
> +function setup_schedstat() {
> +        echo "Setting up schedstat ."
>
> nit: delete space between "schedstat" and '.'
> ------------------------------
>
> In lpcpu.sh
> <https://github.com/ThinkOpenly/lpcpu/pull/1#discussion_r441773674>:
>
> > +        echo "Setting up cpu_vulnerabilities."
> +       	if [ ! -d  /sys/devices/system/cpu/vulnerabilities ]; then
> +               	echo "Note: cpu_vulnerabilities is not there in /sys."
> +       	fi
> +}
> +
> +function start_cpu_vulnerabilities() {
> +        echo "starting cpu_vulnerabilities." | tee -a $LOGDIR/profile-log.$RUN_NUMBER
> +       	grep . /sys/devices/system/cpu/vulnerabilities/* >> $LOGDIR/cpu_vulnerabilities.$id.$RUN_NUMBER
> +}
> +
> +## schedstat##########################################################################################
> +function setup_schedstat() {
> +        echo "Setting up schedstat ."
> +        if [ ! -f  /proc/schedstat ]; then
> +                echo "Note: schedstat is not there in /proc."
>
> change to "Warning: /proc/schedstat not found."
> ------------------------------
>
> In lpcpu.sh
> <https://github.com/ThinkOpenly/lpcpu/pull/1#discussion_r441773921>:
>
> > +	while [ 1 ]; do cpupower monitor -i $interval ;  done  >> $LOGDIR/cpupower.$id.$RUN_NUMBER &
> +	CPUPOWER_PID=$!
> +	disown $CPUPOWER_PID
> +}
> +
> +function stop_cpupower() {
> +	echo "Stopping cpupower."
> +	kill $CPUPOWER_PID
> +}
> +
> +## cpu_vulnerabilities##########################################################################################
> +
> +function setup_cpu_vulnerabilities() {
> +        echo "Setting up cpu_vulnerabilities."
> +       	if [ ! -d  /sys/devices/system/cpu/vulnerabilities ]; then
> +               	echo "Note: cpu_vulnerabilities is not there in /sys."
>
> change to "Warning: /sys/devices/system/cpu/vulnerabilities not found."
> ------------------------------
>
> In lpcpu.sh
> <https://github.com/ThinkOpenly/lpcpu/pull/1#discussion_r441774542>:
>
> > +##
> +sestatus > $LOGDIR/selinux_status.$id.$RUN_NUMBER
> +
> +
> +## slabtop##########################################################################################
> +function setup_slabtop() {
> +	echo "Setting up slabtop."
> +	SLABTOP=$(which slabtop)
> +	if [ -z "$SLABTOP" ]; then
> +		echo "ERROR: slabtop is not installed.  To correct this problem install the required package for your distribution."
> +		exit 1
> +	fi
> +}
> +
> +function start_slabtop() {
> +	echo "starting slabtop." | tee -a $LOGDIR/profile-log.$RUN_NUMBER
>
> s/starting/Starting/
> ------------------------------
>
> In lpcpu.sh
> <https://github.com/ThinkOpenly/lpcpu/pull/1#discussion_r441774646>:
>
> > +	echo "Stopping slabtop."
> +	kill $ISLABTOP_PID
> +}
> +
> +## cpupower##########################################################################################
> +function setup_cpupower() {
> +	echo "Setting up cpupower ."
> +	CPUPOWER=$(which cpupower)
> +	if [ -z "$CPUPOWER" ]; then
> +		echo "ERROR: cpupower is not installed."
> +		exit 1
> +	fi
> +}
> +
> +function start_cpupower() {
> +	echo "starting cpupower." | tee -a $LOGDIR/profile-log.$RUN_NUMBER
>
> s/starting/Starting/
> ------------------------------
>
> In lpcpu.sh
> <https://github.com/ThinkOpenly/lpcpu/pull/1#discussion_r441774752>:
>
> > +function stop_cpupower() {
> +	echo "Stopping cpupower."
> +	kill $CPUPOWER_PID
> +}
> +
> +## cpu_vulnerabilities##########################################################################################
> +
> +function setup_cpu_vulnerabilities() {
> +        echo "Setting up cpu_vulnerabilities."
> +       	if [ ! -d  /sys/devices/system/cpu/vulnerabilities ]; then
> +               	echo "Note: cpu_vulnerabilities is not there in /sys."
> +       	fi
> +}
> +
> +function start_cpu_vulnerabilities() {
> +        echo "starting cpu_vulnerabilities." | tee -a $LOGDIR/profile-log.$RUN_NUMBER
>
> s/starting/Starting/
> ------------------------------
>
> In lpcpu.sh
> <https://github.com/ThinkOpenly/lpcpu/pull/1#discussion_r441774940>:
>
> > +
> +function start_cpu_vulnerabilities() {
> +        echo "starting cpu_vulnerabilities." | tee -a $L [...]

2020-06-19 13:24 UTC, merged